account/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth.views import LoginView,LogoutView,PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView
app_name = 'tutorial'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html'),name='login'),
    path('logout/', LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    path('register/',views.register,name='register'),
    path('profile/',views.view_profile,name='view_profile'),
    path('profile/<int:num>/',views.view_profile,name='view_profile_with_id'),
    path('profile/edit/',views.edit_profile,name='edit_profile'),
    path('changepassword/',views.change_password,name='change_password'),
    path('resetpassword/',PasswordResetView.as_view(template_name='account/reset_password.html'), name='reset_password'),
    path('resetpassword/done/',PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('resetpassword/complete/',PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'^resetpassword/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),


]

home/urls.py
from django.urls import path
from .views import HomeView
from . import views
app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('connect/<str:alpha>/<int:num>/', views.change_friends, name='change_friends'),
    path('message/<int:num>/', views.chat, name='chat'),
    path('mytweet/', views.tweets, name='tweets'),
    path('timeline/', views.publictweets, name='publictweets'),

]

tutorial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from Api import views

urlpatterns = [
    # path('', views.login_redirect,name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls',namespace='tutorial')),
    path('home/', include('home.urls',namespace='home')),
    path('user/', include('Api.api_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = format_suffix_patterns(urlpatterns)

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user',null=True)
    post = models.CharField(max_length=360)


class Friends(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.OneToOneField(User,on_delete=models.CASCADE, null=True, related_name='owner')
    @classmethod
    def make_friend(cls,current_user,new_friend):
        friend,created=cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls,current_user,new_friend):
         friend,created=cls.objects.get_or_create(
             current_user=current_user
         )
         friend.users.remove(new_friend)
    class Meta:
        verbose_name_plural='Friends'

class Tweet(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date=models.DateTimeField(auto_now=True,auto_now_add=False)

home/forms.py
from django import forms
from .models import Post,Message,Tweet

class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'write a post...'
        }
    ))
    class Meta:
        model = Post
        fields =['post']

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['post']

class TweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ['text']

home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from .forms import HomeForm
from .models import Post,Friends
from django.contrib.auth.models import User
from .forms import MessageForm,TweetForm
from home.models import Message,Tweet

# def home(request):
#
#     return render(request,'home/home.html')

# Create your views here.
class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request):
        form = HomeForm()
        posts = Post.objects.all().order_by('-created')
        friends = User.objects.exclude(id=request.user.id)
        list=Friends.objects.get(current_user=request.user)
        lists = list.users.all()

        argss = {'form': form, 'posts': posts,'friends':friends, 'lists': lists}
        return render(request, self.template_name, argss)

    def post(self, request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            form.save(commit=True)
            text = form.cleaned_data['post']
            HomeForm()
            return redirect('home:home')

        args = {'form': form,'text':text}
        return render(request, self.template_name, args)


def change_friends(request,alpha,num):
    new_friend = User.objects.get(pk=num)
    if alpha == 'add':
        Friends.make_friend(request.user,new_friend)
    elif alpha == 'remove':
        Friends.lose_friend(request.user,new_friend)
    return redirect('home:home')

def chat(request,num):
    receiver = User.objects.get(pk=num)
    if request.method == 'GET':
        form = MessageForm()
        chatfriend = User.objects.get(pk=num)
        messages = request.user.message_set.filter(receiver__username__icontains=chatfriend)
        chatfriend = chatfriend.message_set.filter(receiver__username__icontains=request.user)
        context = {'messages': messages, 'friendmessages': chatfriend,'receiver':receiver,'form':form}
        return render(request,'home/chat.html', context)

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.sender= request.user
            obj.receiver = receiver
            obj.save()
            return redirect('/home/message/{}/'.format(num))

def tweets(request):
    if request.method=='GET':
        form=TweetForm()
        ttws = Tweet.objects.filter(User__username__icontains=request.user).order_by('-date')
        context = {'tweets':ttws,'form':form}
        return render(request, 'home/tweet.html', context)
    if request.method =='POST':
        form = TweetForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.User=request.user
            obj.save()
            return redirect('home:tweets')

def publictweets(request):
    friends=Friends.objects.get(current_user__id=request.user.id)
    print(friends)

    for friend in friends.users.all():
        for tweet in friend.tweet_set.all():
            print(tweet.text)
    context = {'friends':friends}
    return render(request, 'home/timeline.html', context)

home/templates/home/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'home:home' %}">Home</a>
    <a href="{% url 'tutorial:view_profile_with_id' receiver.id %}">Profile</a>
    <h1>message from {{ request.user.username }} to {{ receiver.username }}</h1>
    {% for message in messages %}
        <li>{{ message.post }}</li>
    {% endfor %}
    <br/>
    <h1>message from {{ receiver.username }} to {{ request.user.username }} </h1>
    {% for message in friendmessages %}
        <li>{{ message.post }}</li>
    {% endfor %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
    </form>


</body>
</html>

home/templates/home/home.html
{% extends 'account/base.html' %}

{% block body %}

    <div style="float: left">
    <h1>this is actually working</h1>
    <form method="post">
        {% csrf_token %}
        {{ forms.errors }}
        {{ form.post }}
        <button type="submit">Submit</button>
    </form>
    {% for post in posts %}
        <h1>{{ post.post }}</h1>
        <p>created on {{ post.created }} by {{ post.user.get_full_name }}</p>
    {% endfor %}

    <h1>These are friend that you may know</h1>
    {% for user in users %}

        <a href="{% url 'tutorial:view_profile_with_id' user.pk %}"><h3>{{ user.first_name }}</h3></a>
        {% if not user in friends %}
        <a href="{% url 'home:change_friends' alpha='add' num=user.pk %}" style="cursor:pointer;"><button>Add friend</button></a>
        {% endif %}
    {% endfor %}
    </div>


    <div style="float:right">
    <h1>Friends</h1>
    {% if friends %}
    {% for friend in friends %}

        <h3><a href="{% url 'tutorial:view_profile_with_id' friend.pk %}">{{ friend.username }}</a>
        ~
        {% if not friend in lists %}
            <a href="{% url 'home:change_friends' 'add' friend.pk %}">follow</a>
        {% endif %}

        </h3>



    {% endfor %}
    {% endif %}

    <h2>Friends Lists</h2>
    {% for list in lists %}
        <li>{{ list.username }} - <a href="{% url 'home:change_friends' 'remove' list.pk %}">unfollow</a> </li>


    {% endfor %}
    </div>

{% endblock %}

home/templates/home/timeline.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'home:home' %}">Home</a>
<h2>Timeline</h2>
    {% for friend in friends.users.all %}
        {% for tweet in friend.tweet_set.all %}
            <li> <b>{{ tweet.User }}</b> on {{ tweet.date }}<br/>
             <b>{{ tweet.text }}</b></li>

            <a href="#">retweet</a>~
            <a href="#">like</a>
        {% endfor %}
    {% endfor %}
</body>
</html>

home/templates/home/tweet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'home:home' %}">Home</a>
    <h1>Tweet</h1>
    {% for tweet in tweets %}
        <li>{{ tweet.text }}</li>
        <li>{{ tweet.date }}</li>
    {% endfor %}

    <form method="post">
        {% csrf_token %}
        {{ form }}<br/>
        <button type="submit">Tweet</button>
    </form>
</body>
</html>